ALTER TABLE news_ingestion_source
    ADD COLUMN content_access_policy VARCHAR(32) NOT NULL DEFAULT 'SUMMARY_ONLY' COMMENT '内容访问策略：SUMMARY_ONLY/SNIPPET_ALLOWED/FULLTEXT_ALLOWED/PDF_ALLOWED/LINK_ONLY/UNKNOWN',
    ADD COLUMN max_age_hours INT NOT NULL DEFAULT 24 COMMENT '最新内容采集窗口小时数',
    ADD COLUMN allow_pdf_download TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许下载PDF：1允许 0禁止',
    ADD COLUMN allow_full_text TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许保存全文：1允许 0禁止',
    ADD COLUMN license_note VARCHAR(1000) COMMENT '来源授权说明';
